### ISSUE TITLE
zsh startup slowdown

### ISSUE THREAD

**Issue by amogus07** [sha1n/path-ethic#39] opened 2023-11-28 19:36 UTC
Sourcing this plugin in .zshrc causes zsh to take 500-600ms longer to start. This is longer than everything else in my .zshrc combined.

**Comment by sha1n** [comment] 2023-11-29 05:36
Hi @amogus07, 

Thanks for reporting this issue. However, I've been using this plugin on an M1 Macbook pro and an Intel Mac mini ever since I developed it and I have never observed anything like that. Sourcing the plugin does very little, so I can't think of a reason why it would take that long.

A few questions:
- Have you tried removing anything else from your profile and check whether it still takes that long to load?
- Do you have any security software that maybe gets in the way of file access for scanning? The main plugin script sources a few other scrips and attempts to load a preset file if one exists.
- Have you tried timing the command `source <path to plugin>/path-ethic.plugin.zsh`?

**Comment by amogus07** [comment] 2023-11-29 06:07
@sha1n Timing it doesn't seem to work since `source` is a shell built-in command. The only way I found to time it is by measuring the startup time of zsh with and without path-ethic using zsh-startup-timer. But just sourcing the file from an interactive shell seems to happen instantly.

**Comment by sha1n** [comment] 2023-11-30 19:46
@amogus07 I added `echo $(gdate +"%Y-%m-%d %H:%M:%S.%3N")` around the line that loads my entire shell profile and it takes around 50 to 80 milliseconds (M1 macbook pro, `zsh 5.9 (x86_64-apple-darwin23.0)`), and it does a LOT more than loading that specific plugin.

I suggest that you try a similar approach to see if something pops up.

**Comment by sha1n** [comment] 2023-12-16 18:06
Closing for lack of information or ability to reproduce.

**Closed as not planned by sha1n** 2023-12-16 18:06 UTC
