### ISSUE TITLE
push results in duplicate PATH elements

### ISSUE THREAD

**Issue by keturn** [sha1n/path-ethic#40] opened 2024-09-14 20:47 UTC
Reproduction is something like:

```zsh
peth push A
pesh push B
echo $PATH
```
and you end up with `B:A:A:…`

I think this is because the `strip_original_path` function assumes it can take all of the HEAD off of PATH, but the push function already modified HEAD _before_ that was called, and that makes the `##` match ineffective.

I didn't quite figure out how to run the project's tests.

**Comment by sha1n** [comment] 2024-09-16 19:15
Thanks for reporting @keturn! 
Indeed I was able to reproduce that behavior. You are more than welcome to open a PR that fixes it if you know where the problem is already. Otherwise, I will take a look sometime hopefully soon.

After you sync the project submodules, you can run the tests by executing `make test`. You can see how it is done in [ci.yml](https://github.com/sha1n/path-ethic/blob/master/.github/workflows/ci.yml). However the tests are pretty basic, and primarily designed to make sure the scripts work together sanely and verify very basic functionality. Testing shell scripts is not very common, so if you get lost and still want to PR, we can collaborate on the PR.

10x

**Comment by sha1n** [comment] 2024-09-20 10:40
Resolved by #41

**Closed as completed by sha1n** 2024-09-20 10:40 UTC
